name: Build Docker Image on Release
on:
  pull_request:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install pyyaml
      run: |
        python -m pip install pyyaml

    - name: Build Docker image
      run: |
        DOCKER_IMAGE_NAME=$(python -c "
        import yaml
        try:
            with open('infra/config/app_config.yaml', 'r') as config_file:
                config = yaml.safe_load(config_file)
                docker_image_name = config.get('docker_image_name', 'default_image_name')
                if not docker_image_name:
                    raise ValueError('Docker image name is not defined in app_config.yaml')
                print(docker_image_name)
        except FileNotFoundError:
            print('Error: app_config.yaml not found.')
            exit(1)
        except yaml.YAMLError:
            print('Error: Invalid YAML format in app_config.yaml.')
            exit(1)
        except ValueError as e:
            print(f'Error: {str(e)}')
            exit(1)
        ")
        docker build -t "$DOCKER_IMAGE_NAME" -f "infra/docker/Dockerfile" .

    - name: Move Docker image to obj directory
      run: |
        mkdir -p infra/obj
        mv $DOCKER_IMAGE_NAME infra/obj/
