name: Push Docker Image to GitHub Packages

on:
  pull_request:
    branches:
      - release

jobs:
  push_to_packages:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install pyyaml
      run: |
        python -m pip install pyyaml

    - name: Build Docker image
      run: |
        DOCKER_IMAGE_NAME=$(python -c "
        import yaml
        try:
            with open('infra/config/app_config.yaml', 'r') as config_file:
                config = yaml.safe_load(config_file)
                docker_image_name = config.get('docker_image_name', 'defaultimagename')
                if not docker_image_name:
                    raise ValueError('Docker image name is not defined in app_config.yaml')
                print(docker_image_name)
        except FileNotFoundError:
            print('Error: app_config.yaml not found.')
            exit(1)
        except yaml.YAMLError:
            print('Error: Invalid YAML format in app_config.yaml.')
            exit(1)
        except ValueError as e:
            print(f'Error: {str(e)}')
            exit(1)
        ")
        if [ -z "$DOCKER_IMAGE_NAME" ]; then
            echo "Error: Docker image name is empty."
            exit 1
        fi
        docker build -t $DOCKER_IMAGE_NAME -f infra/docker/Dockerfile .

    - name: Print Docker image name
      run: |
        echo "DOCKER_IMAGE_NAME: ${DOCKER_IMAGE_NAME}"
        
    - name: Log in to GitHub Packages
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

    - name: Push Docker image to GitHub Packages
      run: |
        docker push docker.pkg.github.com/wingemo/template/${DOCKER_IMAGE_NAME}:1
