name: Build Docker Image on Release

on:
  push:
    branches:
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository's code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Set up Python environment

    - name: Build Docker image
      run: |
        DOCKER_IMAGE_NAME=$(python -c "
        import yaml
        try:
            with open('Infrastructure/config/app_config.yaml', 'r') as config_file:
                config = yaml.safe_load(config_file)
                docker_image_name = config.get('docker_image_name', 'default_image_name')
                if not docker_image_name:
                    raise ValueError('Docker image name is not defined in app_config.yaml')
                print(docker_image_name)
        except FileNotFoundError:
            print('Error: app_config.yaml not found.')
            exit(1)
        except yaml.YAMLError:
            print('Error: Invalid YAML format in app_config.yaml.')
            exit(1)
        except ValueError as e:
            print(f'Error: {str(e)}')
            exit(1)
        ")
                docker build -t "$DOCKER_IMAGE_NAME" -f "Infrastructure/Docker/Dockerfile" .
